### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Wulfklaue** [Pure-D/serve-d#4]
Installed serve-d at work on mobile VSC 1.15.1. Only on other extension installed (vscode-icons):

```
Extension Host] vscode-icons is active!
/J:/PortableApps/VSCodePortable/App/VSCode64/resources/app/out/vs/workbench/workbench.main.js:28 Extension host terminated unexpectedly. Please reload the window to recover.
e.doShow @ /J:/PortableApps/VSCodePortable/App/VSCode64/resources/app/out/vs/workbench/workbench.main.js:28
/J:/PortableApps/VSCodePortable/App/VSCode64/resources/app/out/vs/workbench/workbench.main.js:29 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
t.onExit @ /J:/PortableApps/VSCodePortable/App/VSCode64/resources/app/out/vs/workbench/workbench.main.js:29
index.js:5 [uncaught exception]: Error: write EPIPE
onError @ index.js:5
index.js:5 Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:715:26)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Socket.Writable.write (_stream_writable.js:245:11)
    at Socket.write (net.js:661:40)
    at Immediate.<anonymous> (file:///J:/PortableApps/VSCodePortable/App/VSCode64/resources/app/out/vs/workbench/workbench.main.js:28:191009)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
onError @ index.js:5
events.js:160 Uncaught Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:715:26)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Socket.Writable.write (_stream_writable.js:245:11)
    at Socket.write (net.js:661:40)
    at Immediate.<anonymous> (file:///J:/PortableApps/VSCodePortable/App/VSCode64/resources/app/out/vs/workbench/workbench.main.js:28:191009)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
```

**Comment by Wulfklaue** [comment]
Same issue with Code-D. Also got a error from VSC this time, that did not happen with serve-d:

`J:\PortableApps\VSCodePortable\App\VSCode64\resources\app\node_modules\vscode-textmate\release\main…:2431 [4] - Grammar is in an endless loop - Grammar is not advancing, nor is it pushing/popping
scanNext @ J:\PortableApps\VSCodePortable\App\VSCode64\resources\app\node_modules\vscode-textmate\release\main…:2431
_tokenizeString @ J:\PortableApps\VSCodePortable\App\VSCode64\resources\app\node_modules\vscode-textmate\release\main…:2321
Grammar._tokenize @ J:\PortableApps\VSCodePortable\App\VSCode64\resources\app\node_modules\vscode-textmate\release\main…:2089
Grammar.tokenizeLine2 @ J:\PortableApps\VSCodePortable\App\VSCode64\resources\app\node_modules\vscode-textmate\release\main…:2059
e.tokenize2 @ TMSyntax.ts:301
t._updateTokensUntilLine @ textModelWithTokens.ts:345
(anonymous) @ textModelWithTokens.ts:312
t._withModelTokensChangedEventBuilder @ textModelWithTokens.ts:156
t._revalidateTokensNow @ textModelWithTokens.ts:275
(anonymous) @ textModelWithTokens.ts:249
extensionHost.ts:335 [Extension Host] vscode-icons is active!
messageService.ts:125 Extension host terminated unexpectedly. Please reload the window to recover.
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
t.onExit @ extensionHost.ts:378
(anonymous) @ extensionHost.ts:196
emitTwo @ events.js:106
emit @ events.js:191
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215
extensionHost.ts:386 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
t.onExit @ extensionHost.ts:386
(anonymous) @ extensionHost.ts:196
emitTwo @ events.js:106
emit @ events.js:191
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215
webfreak.gallerycdn.vsassets.io/extensions/webfreak/code-d/0.16.2/1499506474476/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://webfreak.gallerycdn.vsassets.io/extensions/webfreak/code-d/0.16.2/1499506474476/Microsoft.VisualStudio.Services.Icons.Default net::ERR_BLOCKED_BY_CLIENT
webfreak.gallery.vsassets.io/_apis/public/gallery/publisher/webfreak/extens…/code-d/0.16.2/assetbyname/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://webfreak.gallery.vsassets.io/_apis/public/gallery/publisher/webfrea…on/code-d/0.16.2/assetbyname/Microsoft.VisualStudio.Services.Icons.Default net::ERR_BLOCKED_BY_CLIENT`

DMD32 D Compiler v2.074.0
LDC - the LLVM D compiler (1.3.0-beta1)

**Comment by WebFreak001** [comment]
uh there is no error information in there. If you use code-d-beta, can you open the output log to see if there is anything?

**Comment by Wulfklaue** [comment]
The output did not have anything useful. I trace the issue to Serve-d being compiled with LDC 13 beta 1. With a more recent version, ( final LDC 13 ), the constant crashing issues are gone. So it was a flaw in LDC 1.3.0-beta 1 that crashed the compiled executable.
